goFish: cardshuffle.o compranout.o compturn.o computermatchingcards.o drawCards.o initializingarray.o main.o modulo.o playermatchingcards.o playerranout.o playerturn.o storeCards.o winnercheck.o
		gcc -o goFish cardshuffle.o compranout.o compturn.o computermatchingcards.o drawCards.o initializingarray.o main.o modulo.o playermatchingcards.o playerranout.o playerturn.o storeCards.o winnercheck.o


cardshuffle.o: cardshuffle.s
	gcc -c -g cardshuffle.s

compranout.o: compranout.s
	gcc -c -g compranout.s

compturn.o: compturn.s
	gcc -c -g compturn.s

computermatchingcards.o: computermatchingcards.s
	gcc -c -g computermatchingcards.s

drawCards.o: drawCards.s
	gcc -c -g drawCards.s


initializingarray.o: initializingarray.s
	gcc -c -g initializingarray.s

main.o: main.s
	gcc -c -g main.s

modulo.o: modulo.s
	gcc -c -g modulo.s

playermatchingcards.o: playermatchingcards.s
	gcc -c -g playermatchingcards.s

playerranout.o: playerranout.s
	gcc -c -g playerranout.s

playerturn.o: playerturn.s
	gcc -c -g playerturn.s

storeCards.o: storeCards.s
	gcc -c -g storeCards.s

winnercheck.o: winnercheck.s
	gcc -c -g winnercheck.s